NullPointerException in GarbageCollector.scan if no DataStore configured
I am running the garbage collector in a separate thread every 5 minutes.             GarbageCollector gc SessionImpl mSession .createDataStoreGarbageCollector             gc.scan             gc.stopScan             int du gc.deleteUnused When using Jackrabbit v1.5.2 I get sometimes a null pointer exception java.lang.NullPointerException         at org.apache.jackrabbit.core.data.GarbageCollector.scan GarbageCollector.java 153 Hi Did you configure a data store How does the repository.xml look like Do you have any elements in the data store Regards Thomas Hello Thomas I looked to the repository.xml. You are right the repository.xml wasn t configured to use the datastore. Is there a programmatic way to detect if the GarbageCollector could run Greetings    Jacco programmatic way to detect Yes. If this is null then there is no data store RepositoryImpl s.getRepository .getDataStore Anyway the exception you get is not very clear. What about this throws a RepositoryException SessionImpl mSession .createDataStoreGarbageCollector No data store configured. Anyway the exception you get is not very clear. What about this throws a RepositoryException SessionImpl mSession .createDataStoreGarbageCollector No data store configured. Personally I would like that createDataStoreGarbageCollector returns a null when no collector could be created but then this is more a matter of style I guess. Committed in 745534 trunk GarbageCollector.scan now throws a RepositoryException with the message No DataStore configured. instead of a NullPointerException.I saw that one of the tests first calls session.createDataStoreGarbageCollector and then gc.getDataStore to check if the data store is configured. Existing applications could do that as well so it s probably better not to throw an exception or return null in createDataStoreGarbageCollector .
