Repository.login throws IllegalStateException
Calling any login method on Repository instance which has been shut down throws an IllegalStateException which is caused by the RepositoryImpl.sanityCheck method. This exception is unexpected by callers of the login method which is specified to throw one of LoginException NoSuchWorkspaceException and RepositoryException. In particular the spec says that a RepositoryException is thrown if another error occurs . So I suggest to modify the RepositoryImpl.login Credentials String as follows patch against trunk Index usr src jackrabbit trunk jackrabbit-core src main java org apache jackrabbit core RepositoryImpl.java usr src jackrabbit trunk jackrabbit-core src main java org apache jackrabbit core RepositoryImpl.java revision 706543 usr src jackrabbit trunk jackrabbit-core src main java org apache jackrabbit core RepositoryImpl.java working copy -1358 6 1358 8           catch AccessDeniedException ade               authenticated subject is not authorized for the specified workspace              throw new LoginException Workspace access denied ade catch RuntimeException re throw new RepositoryException re.getMessage re           finally              shutdownLock.readLock .release           1 1How about this alternative patch that makes sanityCheck directly throw a RepositoryException This way we don t need to explicitly catch and rethrow the exception. Note that I also removed the sanityCheck call from a few protected getter methods. Public methods that cause those getters to be invoked have already called sanityCheck so it s safe to drop these extra calls.Looks good to me too and makes perfect sense.Patch applied in revision 733080. Targeting for 1.5.1.I might be wrong but I seem to remember this is the exception i got with JCR-1778 which might thus be irrelevant now Merged also to the 1.4 branch in revision 734370.
