VersionManager lock not released in some circumstances
In some circumstances it is possible that lock is not released in VersionManager.checkin method. There is following block of code in checkin nethod         aquireReadLock         try               .....          catch IllegalStateException e             releaseReadLock             throw new RepositoryException Unable to start edit operation.          Lock release should be in finally block to make sure that lock is released when unexpected exception is thrown. In our environment we are getting NPE in mentioned block of code it results in persisten lock. No versioning operation is possible and our application server is running ot of threads all threads are locked . Attached simple patch solving this issue.You re right the release should be in the finally block.Patch applied in revision 475683. Thanks for spotting this Hmm actually the change was incorrect. The code after the try-catch-finally block expects the read lock to still be acquired so releasing it in the catch block before throwing an exception was OK but not in the finally block. This of course still leaves open the question of what to do with unexpected RuntimeExceptions. I m reverting this change and hope to fix this together with JCR-546.Resolved in revision 478645 as a side effect of the JCR-546 fix. As discussed in JCR-546 this change will not yet be included in the 1.1.1 release.
