benchmark tests always fail on windows because directory cannot be removed
This seems to be a bug recently introduced. I have no idea what s wrong. Attached is a log file reproduces everytime. Only fails for Lucene trunk seems to be related to the additional cleanupo by the removal of new IndexSearcher directory . hudson needs a space in its folder too The problem is BenchmarkTestCase i m sure i introduced the bug when i fixed another bug it used TEMP DIR directly . OK it fails even if you have no space in the directory. So i m guessing this test leaves a file open outside of mockdirectorywrapper We need FileSystem.setDefault new MockWindowsFileSystem ... It looks to me like the problem is inside LineDocSourceTest doIndexAndSearchTest i ran the test with -Dtestmethod testWithDocsName and it passes if i comment out the call to this method. Here the complete I O event log created by sysinternals process monitor when running test TestLineDocSource When LuceneTestCase cannot delete a file that it wants to I m gonna see if we can improve the output for starters. This would make it easier to debug issues like this. with this patch the benchmark tests pass most of the time on my windows computer. But sometimes they still fail with the same filenames involved ... I have no idea why. By the way this is the reason these tests fail now http svn.apache.org viewvc lucene dev branches lucene2621 modules benchmark src test org apache lucene benchmark BenchmarkTestCase.java view diff r1 1201966 r2 1201967 pathrev 1201967 Before they just created files underneath TEMP DIR directly and were not closing things and were silently wrong... so the problems have been here a while. Setting affects 3.x becuase i m gonna backport my previous fix that unravelled this problem. Patch fixes the problem in LineDocSourceTest - add tasks.close otherwise LDS keeps a reader open on the file . I intend to commit shortly after verifying all tests pass and no other such changes are required. Committed rev 1204826 3x . Ported changes to trunk in rev 1204828. I still think we should also commit Robert s patch. You re right I didn t notice it. I ll work on it now. Committed Robert s changes to trunk rev 1204851. However after porting to 3x and running the tests LineDocSourceTest consistently fails with this ant test -Dtestcase LineDocSourceTest -Dtests.seed -2895bf521e2206c 0 4f1f278a279ce441 I m investigating don t know if it fails on trunk too yet . Ok found it testInvalidFormat expected exceptions to be thrown while the algorithm runs and so tasks.close wasn t called. I ll change the code to close in a try-finally for all Closeable resources. Committed test fixes to 3x and trunk. Shai thanks for getting to the bottom of this Bulk close after release of 3.5
