DirectoryTaxonomyWriter should throw a proper exception if it was closed
DirTaxoWriter may throw random exceptions NPE Already Closed - depend on what API you call after it has been closed rollback. We should detect up front that it is already closed and throw AlreadyClosedException. Also on LUCENE-3573 Doron pointed out a problem with DTW.rollback Ð it should call close rather than refreshReader. I will fix that as well in this issue. Patch fixes rollback and adds a final ensureOpen that is called from all the public API methods. In addition it adds two tests to DirTaxoWriterTest. All tests pass. I intend to commit this shortly. Committed revision 1202592 3x . Committed revision 1202593 trunk . Bulk close after release of 3.5
