<!-- 
RSS generated by JIRA (5.2.8#851-sha1:3262fdc28b4bc8b23784e13eadc26a22399f5d88) at Sat Jul 27 05:36:15 UTC 2013

It is possible to restrict the fields that are returned in this document by specifying the 'field' parameter in your request.
For example, to request only the issue key and summary add field=key&field=summary to the URL of your request.
For example:
https://issues.apache.org/jira/si/jira.issueviews:issue-xml/JCR-2749/JCR-2749.xml?field=key&field=summary
-->
<rss version="0.92" >
<channel>
    <title>ASF JIRA</title>
    <link>https://issues.apache.org/jira</link>
    <description>This file is an XML representation of an issue</description>
    <language>en-uk</language>    <build-info>
        <version>5.2.8</version>
        <build-number>851</build-number>
        <build-date>26-02-2013</build-date>
    </build-info>

<item>
            <title>[JCR-2749] Closing a session twice shouldn&apos;t write a warning in the log</title>
                <link>https://issues.apache.org/jira/browse/JCR-2749</link>
                <project id="10591" key="JCR">Jackrabbit Content Repository</project>
                        <description>When closing a session twice the following warning is written to the log file as of &lt;a href=&quot;https://issues.apache.org/jira/browse/JCR-2741&quot; title=&quot;Improved logging for session operations&quot;&gt;&lt;strike&gt;JCR-2741&lt;/strike&gt;&lt;/a&gt;:&lt;br/&gt;
&lt;br/&gt;
&amp;quot;This session has already been closed. See the chained exception for a trace of where the session was closed.&amp;quot;&lt;br/&gt;
&lt;br/&gt;
I think the second &amp;quot;close()&amp;quot; should simply be ignored, without warning.&lt;br/&gt;
</description>
                <environment></environment>
            <key id="12474152">JCR-2749</key>
            <summary>Closing a session twice shouldn&apos;t write a warning in the log</summary>
                <type id="4" iconUrl="https://issues.apache.org/jira/images/icons/issuetypes/improvement.png">Improvement</type>
                                <priority id="4" iconUrl="https://issues.apache.org/jira/images/icons/priorities/minor.png">Minor</priority>
                    <status id="6" iconUrl="https://issues.apache.org/jira/images/icons/statuses/closed.png">Closed</status>
                    <resolution id="1">Fixed</resolution>
                                <assignee username="tmueller">Thomas Mueller</assignee>
                                <reporter username="tmueller">Thomas Mueller</reporter>
                        <labels>
                    </labels>
                <created>Wed, 15 Sep 2010 09:44:16 +0100</created>
                <updated>Tue, 8 Nov 2011 15:52:00 +0000</updated>
                    <resolved>Thu, 23 Sep 2010 12:54:29 +0100</resolved>
                            <version>2.2</version>
                                <fixVersion>2.2</fixVersion>
                                <component>jackrabbit-core</component>
                        <due></due>
                    <votes>0</votes>
                        <watches>0</watches>
                                                    <comments>
                    <comment id="12909655" author="jukkaz" created="Wed, 15 Sep 2010 09:58:31 +0100"  >A duplicate close() call is always a sign of an error somewhere, so I&amp;#39;d rather not just silently ignore that situation.&lt;br/&gt;
&lt;br/&gt;
If the warning log is troublesome, we can downgrade it to a debug message.</comment>
                    <comment id="12909660" author="tmueller" created="Wed, 15 Sep 2010 10:04:55 +0100"  >The warning (with stack trace) is even logged if the session is only closed once, as in:&lt;br/&gt;
&lt;br/&gt;
TransientRepository rep = new TransientRepository();&lt;br/&gt;
Session s = rep.login(new SimpleCredentials(&amp;quot;&amp;quot;, new char[0]));&lt;br/&gt;
s.logout();</comment>
                    <comment id="12909661" author="mduerig" created="Wed, 15 Sep 2010 10:07:42 +0100"  >I double Jukka&amp;#39;s point here. However I agree that the message is not helpful in the logs (to the end user that is). The message is merely some developer&amp;#39;s aid. &lt;br/&gt;
&lt;br/&gt;
I&amp;#39;d make it a debug message in the field. For unit tests and integration test&amp;#39;s however I&amp;#39;d make it a failure (i.e throw an AssertionError).&lt;br/&gt;
&lt;br/&gt;
</comment>
                    <comment id="12909664" author="mduerig" created="Wed, 15 Sep 2010 10:10:38 +0100"  >For TransientRepository this seems to be a separate issue to. AFAIK TransientRepository keeps track of its sessions and closes them automatically. So in your example the session is really closed twice which is indeed wrong. </comment>
                    <comment id="12909667" author="tmueller" created="Wed, 15 Sep 2010 10:19:53 +0100"  >If we do really want a warning in the log (which I think is not necessary, I think debug is enough) then we need both places where the session was closed. Just one stack trace is not enough.&lt;br/&gt;
&lt;br/&gt;
I think throwing an AssertionError while testing is OK, but how? Do we have a mechanism (maybe a system property) to distinguish between test and runtime?</comment>
                    <comment id="12909669" author="tmueller" created="Wed, 15 Sep 2010 10:26:18 +0100"  >Proposed patch</comment>
                    <comment id="12909670" author="tmueller" created="Wed, 15 Sep 2010 10:30:10 +0100"  >I don&amp;#39;t think the problem only occurs with TransientRepository. It occurred with a repository implementation that extends RepositoryImpl.</comment>
                    <comment id="12909676" author="jukkaz" created="Wed, 15 Sep 2010 10:45:21 +0100"  >If the warnings are caused by the automatic shutdown procedures of TransientRepository or other repository implementations, then we should fix those errors instead of hiding the issue by lowering the log level.&lt;br/&gt;
&lt;br/&gt;
I&amp;#39;m OK to also including the stack trace of the second close in the log, even though Logback already gives us that as a configuration option.</comment>
                    <comment id="12909679" author="mduerig" created="Wed, 15 Sep 2010 10:50:47 +0100"  >I&amp;#39;m generally fine with lowering to debug level. However I fear this will also hide potential problems during development instead on forcing us to fix them. This is why I proposed to throw an AssertionError in dev mode. I think we have a system property for integration testing already which could be used here. Jukka?</comment>
                    <comment id="12909683" author="tmueller" created="Wed, 15 Sep 2010 10:55:07 +0100"  >The main problem is fixed in revision 997244 - if you want to further improve things please go ahead.</comment>
                    <comment id="12909691" author="jukkaz" created="Wed, 15 Sep 2010 11:27:34 +0100"  >I looked deeper into this and it looks like the warning from &amp;quot;new TransientRepository().login().logout()&amp;quot; does not come from this logout() call, but actually from the fact that the repository is attempting to repeatedly close the system session! This is because of the hacks used in access control and data store garbage collection code where the system session of a workspace is marked as a normal active session to prevent the workspace janitor from disposing a workspace. During shutdown this makes the repository treat the system session as an unclosed user session, which then gets automatically closed before the repository later on correctly attempts to close the system session. The system session should only ever get closed in the WorkspaceInfo.doDispose() method.&lt;br/&gt;
&lt;br/&gt;
Assuming we fix the above problem, is there still a need to keep the log level at debug? As shown by this case the warnings do help us spot real problems.</comment>
                    <comment id="12909700" author="tmueller" created="Wed, 15 Sep 2010 12:51:22 +0100"  >Thanks a lot Jukka, great that you found the root cause!&lt;br/&gt;
&lt;br/&gt;
&amp;gt; Assuming we fix the above problem, is there still a need to keep the log level at debug?&lt;br/&gt;
&lt;br/&gt;
For me personally, it&amp;#39;s not that important. &lt;br/&gt;
&lt;br/&gt;
My fear is the log file will be less relevant if it contains stack traces of things that are viewed as unproblematic by many (most?) developers (such as closing a resource twice). So I vote to keep it at debug level. &lt;br/&gt;
&lt;br/&gt;
But I agree with Michael: while running unit tests, it should throw an AssertionError. Therefore, it would have broke the build.</comment>
                    <comment id="12909736" author="mreutegg" created="Wed, 15 Sep 2010 15:06:01 +0100"  >I&amp;#39;d like to keep it on warn, because that&amp;#39;s exactly what it is. nothing&amp;#39;s broken, it still works but something is wrong anyway. if you are not interested in these kind of messages you can simply ignore warnings and only look at error messages.&lt;br/&gt;
&lt;br/&gt;
enabling assertions is done with a jvm option (-ea) and is usually done when running tests.</comment>
                    <comment id="12909918" author="jukkaz" created="Wed, 15 Sep 2010 23:22:14 +0100"  >In revision 997496 I fixed the problem with duplicate closing of the system session.&lt;br/&gt;
&lt;br/&gt;
In revision 997518 I turned the log level back to warnings as I believe the above fix addresses the most prominent case of duplicate closing. The log messages now also come with additional instructions on what to look for in order to fix the problems.&lt;br/&gt;
&lt;br/&gt;
I agree about the concern over the relevancy of log messages, but I&amp;#39;d only lower the log level if there remain other prominent cases where a more proper fix is too expensive.&lt;br/&gt;
&lt;br/&gt;
Re: assertions; IMO assertions are best used as logic guards for code that you control entirely - loop and class invariants, etc. In this case we&amp;#39;re mostly guarding against bad behavior by client code, and thus I think that logging warnings or in more extreme cases throwing exceptions are more appropriate solutions than assertions.&lt;br/&gt;
</comment>
                    <comment id="12910000" author="tmueller" created="Thu, 16 Sep 2010 04:45:51 +0100"  >Thanks for fixing the root cause of the problem!&lt;br/&gt;
&lt;br/&gt;
a) Is it illegal (according to the spec) to call close() multiple times? I think it isn&amp;#39;t, but I might be wrong.&lt;br/&gt;
&lt;br/&gt;
b) The AssertionError was supposed to be thrown calling close() multiple times while running Jackrabbit test cases only (this is detected using a system property). Personally, I actually didn&amp;#39;t think about using the &amp;quot;assert&amp;quot; keyword, because of a). Instead, I would use &amp;quot;if (runningJackrabbitTestCases) throw new AssertionError(...)&amp;quot;. That means a client would never get this exception, but the exception would be thrown when running Jackrabbit test cases, no matter if -ea is used or not.&lt;br/&gt;
</comment>
                    <comment id="12910041" author="mduerig" created="Thu, 16 Sep 2010 09:18:32 +0100"  >Regarding b): this is exactly what I had in mind originally. Now that log levels are back to warn, I think I can live with the current solution also.</comment>
                    <comment id="12910047" author="jukkaz" created="Thu, 16 Sep 2010 09:38:01 +0100"  >a) It&amp;#39;s not illegal, but doing so is practically always a sign of some resource management error. Thus I think a warning is in place, just like when we log a warning when a client forgets to close a session (see &lt;a href=&quot;https://issues.apache.org/jira/browse/JCR-1216&quot; title=&quot;Unreferenced sessions should get garbage collected&quot;&gt;&lt;strike&gt;JCR-1216&lt;/strike&gt;&lt;/a&gt;).&lt;br/&gt;
&lt;br/&gt;
b) Since a duplicate logout() is not strictly speaking illegal (see a), an assertion is IMHO the wrong thing to use. Generally speaking nothing that a JCR client can produce by invoking standard JCR methods should ever be able to trigger an assertion. StackOverflow summarizes this nicely: &amp;quot;Use assertions for internal logic checks within your code, and normal exceptions for error conditions outside your immediate code&amp;#39;s control.&amp;quot; (&lt;a href=&quot;http://stackoverflow.com/questions/1276308/exception-vs-assertion&quot;&gt;http://stackoverflow.com/questions/1276308/exception-vs-assertion&lt;/a&gt;)&lt;br/&gt;
&lt;br/&gt;
Also, I&amp;#39;d rather avoid extra behaviour that&amp;#39;s only activated during test runs (I know we have some of them in the codebase), since such code erodes the purpose of testing by making the test system behave differently than a production system. If we want a way for the test suite to check against these situations, we should either make it scan the log file for logged warnings or add a more generic mechanism by which a client application can specify custom handling of problems like this.</comment>
                    <comment id="12913986" author="jukkaz" created="Thu, 23 Sep 2010 12:54:29 +0100"  >Resolving as fixed, since the &amp;quot;new TransientRepository().login().logout()&amp;quot; sequence no longer logs a warning.</comment>
                </comments>
                    <attachments>
                    <attachment id="12454639" name="sessionClose.txt" size="1083" author="tmueller" created="Wed, 15 Sep 2010 10:26:18 +0100" />
                </attachments>
            <subtasks>
        </subtasks>
                <customfields>
                                <customfield id="customfield_12310310" key="com.atlassian.jira.toolkit:attachments">
                <customfieldname>Attachment count</customfieldname>
                <customfieldvalues>
                    <customfieldvalue>1.0</customfieldvalue>
                </customfieldvalues>
            </customfield>
                                                                <customfield id="customfield_12310220" key="com.atlassian.jira.ext.charting:firstresponsedate">
                <customfieldname>Date of First Response</customfieldname>
                <customfieldvalues>
                    <customfieldvalue>Wed, 15 Sep 2010 08:58:31 +0000</customfieldvalue>

                </customfieldvalues>
            </customfield>
                                                                                                        <customfield id="customfield_12310420" key="com.pyxis.greenhopper.jira:gh-global-rank">
                <customfieldname>Global Rank</customfieldname>
                <customfieldvalues>
                    <customfieldvalue>97853</customfieldvalue>
                </customfieldvalues>
            </customfield>
                                            <customfield id="customfield_12310920" key="com.pyxis.greenhopper.jira:gh-global-rank">
                <customfieldname>Rank</customfieldname>
                <customfieldvalues>
                    <customfieldvalue>280288</customfieldvalue>
                </customfieldvalues>
            </customfield>
                                                                                    <customfield id="customfield_12310222" key="com.atlassian.jira.ext.charting:timeinstatus">
                <customfieldname>Time in Status</customfieldname>
                <customfieldvalues>
                    
                </customfieldvalues>
            </customfield>
                            </customfields>
    </item>
</channel>
</rss>